### ISSUE TITLE
Regarding Joint Pyramid Network

### ISSUE THREAD

**Issue by deepseek** [helakim/goblin-ai#1]
@helakim 
Regarding the Joint Pyramid Network,

- When will you release the Train & Inference code?
- Can JYP detect long text-lines?
- How does it compare to other text detection methods, perhaps on icdar 2015

**Comment by helakim** [comment]
Q-1) When will you release the Train & Inference code?

A-1) Sorry I am currently very busy due to iccv 2019 

Q-2) Can JYP detect long text-lines?

A-2) Please explain in detail

Q-3) How does it compare to other text detection methods, perhaps on icdar 2015

A-3) 
The Pure JYP indeed only achieve a H-mean of 83.4%  The  7~8% improvement in our JYP may come from trick
  - Data Argumentation
  - Multi Scale (for like cascade)
  - bayesian hyperparameter optimization
  - Some bag of trick

**Comment by deepseek** [comment]
1-  so after iccv 2019, will you then release the Train & Inference code?
2- Does JYD focus on detecting words only, or it it can be trained to detect entire text-lines.
